### ISSUE TITLE
Reporting: Track API Key Usage

### ISSUE THREAD

**Issue by hofq** [bat-bs/openai-proxy#8]
## Kosten per
- [ ] Firma
- [x] User
- [X] API-Key #12 
- [x] Projekt: Notiz am API Key
- [x] Model/ Request Art #12 
- [x] Last 30d, last 7d last 24h #19 
- [x] This Month, last month × This Year, Last Year #24 

## Allgemeines
- [ ] Filter/ Sortieren Für Table #23 
- [x] Usage per Token für User #20 
- [ ] ORG von Zitadel Env Variablen oder E-Mail Domain ziehen
- [ ] Korrekter Geld Betrag bei Auswertungen (Erst € auch USD)

Als Filteroptionen. Beliebig Kombinierbar
